2014/11/11 14:57:43:630,[5],[]:System.Web.Services.Protocols.SoapException: 服务器无法处理请求。 ---> Unable to open connection to "Microsoft SQL Server 2005, provider V2.0.50215.0 in framework .NET V2.0". ---> 在与 SQL Server 建立连接时出现与网络相关的或特定于实例的错误。未找到或无法访问服务器。请验证实例名称是否正确并且 SQL Server 已配置为允许远程连接。 (provider: SQL Network Interfaces, error: 26 - 定位指定的服务器/实例时出错)
   在 System.Web.Services.Protocols.SoapHttpClientProtocol.ReadResponse(SoapClientMessage message, WebResponse response, Stream responseStream, Boolean asyncCall)
   在 System.Web.Services.Protocols.SoapHttpClientProtocol.Invoke(String methodName, Object[] parameters)
   在 BaseClient.LoginSrv.LoginSrv.CheckUserInfo(UserInfo ui) 位置 E:\project\连云港项目\邮储银行端\源代码\FinancialRegulation\BaseClient\Web References\LoginSrv\Reference.cs:行号 115
   在 BaseClient.LoginClient.CheckUserInfo(UserInfo ui) 位置 E:\project\连云港项目\邮储银行端\源代码\FinancialRegulation\BaseClient\LoginClient.cs:行号 49
   在 MainFrame.LoginVM.CheckLogin() 位置 E:\project\连云港项目\邮储银行端\源代码\FinancialRegulation\MainFrame\LoginVM.cs:行号 142
   在 MainFrame.LoginVM.Confirm() 位置 E:\project\连云港项目\邮储银行端\源代码\FinancialRegulation\MainFrame\LoginVM.cs:行号 223
2014/11/11 14:58:25:525,[5],[]:System.Web.Services.Protocols.SoapException: 服务器无法处理请求。 ---> Unable to open connection to "Microsoft SQL Server 2005, provider V2.0.50215.0 in framework .NET V2.0". ---> 在与 SQL Server 建立连接时出现与网络相关的或特定于实例的错误。未找到或无法访问服务器。请验证实例名称是否正确并且 SQL Server 已配置为允许远程连接。 (provider: SQL Network Interfaces, error: 26 - 定位指定的服务器/实例时出错)
   在 System.Web.Services.Protocols.SoapHttpClientProtocol.ReadResponse(SoapClientMessage message, WebResponse response, Stream responseStream, Boolean asyncCall)
   在 System.Web.Services.Protocols.SoapHttpClientProtocol.Invoke(String methodName, Object[] parameters)
   在 BaseClient.LoginSrv.LoginSrv.CheckUserInfo(UserInfo ui) 位置 E:\project\连云港项目\邮储银行端\源代码\FinancialRegulation\BaseClient\Web References\LoginSrv\Reference.cs:行号 115
   在 BaseClient.LoginClient.CheckUserInfo(UserInfo ui) 位置 E:\project\连云港项目\邮储银行端\源代码\FinancialRegulation\BaseClient\LoginClient.cs:行号 49
   在 MainFrame.LoginVM.CheckLogin() 位置 E:\project\连云港项目\邮储银行端\源代码\FinancialRegulation\MainFrame\LoginVM.cs:行号 142
   在 MainFrame.LoginVM.Confirm() 位置 E:\project\连云港项目\邮储银行端\源代码\FinancialRegulation\MainFrame\LoginVM.cs:行号 223
2014/11/11 16:08:36:876,[5],[]:System.Web.Services.Protocols.SoapException: System.Web.Services.Protocols.SoapException: 服务器无法处理请求。 ---> IBatisNet.DataMapper.Exceptions.DataMapperException: Unable to open connection to "Microsoft SQL Server 2005, provider V2.0.50215.0 in framework .NET V2.0". ---> System.InvalidOperationException: 超时时间已到。超时时间已到，但是尚未从池中获取连接。出现这种情况可能是因为所有池连接均在使用，并且达到了最大池大小。
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 IBatisNet.DataMapper.SqlMapSession.OpenConnection(String connectionString)
   --- 内部异常堆栈跟踪的结尾 ---
   在 IBatisNet.DataMapper.SqlMapSession.OpenConnection(String connectionString)
   在 IBatisNet.DataMapper.Commands.DbCommandDecorator.System.Data.IDbCommand.ExecuteReader()
   在 IBatisNet.DataMapper.MappedStatements.MappedStatement.RunQueryForList[T](RequestScope request, ISqlMapSession session, Object parameterObject, IList`1 resultObject, RowDelegate`1 rowDelegate)
   在 IBatisNet.DataMapper.MappedStatements.MappedStatement.ExecuteQueryForList[T](ISqlMapSession session, Object parameterObject)
   在 IBatisNet.DataMapper.SqlMapper.QueryForList[T](String statementName, Object parameterObject)
   在 Dao.LoginDao.CheckUserInfo(UserInfo ui) 位置 E:\project\连云港项目\邮储银行端\源代码\FinancialRegulation\DAO\LoginDao.cs:行号 19
   在 FinancialRegulationSRV.LoginSrv.CheckUserInfo(UserInfo ui) 位置 E:\project\连云港项目\邮储银行端\源代码\FinancialRegulation\FinancialRegulationSRV\LoginSrv.asmx.cs:行号 35
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Web.Services.Protocols.SoapHttpClientProtocol.ReadResponse(SoapClientMessage message, WebResponse response, Stream responseStream, Boolean asyncCall)
   在 System.Web.Services.Protocols.SoapHttpClientProtocol.Invoke(String methodName, Object[] parameters)
   在 BaseClient.LoginSrv.LoginSrv.CheckUserInfo(UserInfo ui) 位置 E:\project\连云港项目\邮储银行端\源代码\FinancialRegulation\BaseClient\Web References\LoginSrv\Reference.cs:行号 115
   在 BaseClient.LoginClient.CheckUserInfo(UserInfo ui) 位置 E:\project\连云港项目\邮储银行端\源代码\FinancialRegulation\BaseClient\LoginClient.cs:行号 49
   在 MainFrame.LoginVM.CheckLogin() 位置 E:\project\连云港项目\邮储银行端\源代码\FinancialRegulation\MainFrame\LoginVM.cs:行号 142
   在 MainFrame.LoginVM.Confirm() 位置 E:\project\连云港项目\邮储银行端\源代码\FinancialRegulation\MainFrame\LoginVM.cs:行号 223
2014/11/11 16:12:57:259,[5],[]:System.Net.WebException: 操作超时
   在 System.Web.Services.Protocols.WebClientProtocol.GetWebResponse(WebRequest request)
   在 System.Web.Services.Protocols.HttpWebClientProtocol.GetWebResponse(WebRequest request)
   在 System.Web.Services.Protocols.SoapHttpClientProtocol.Invoke(String methodName, Object[] parameters)
   在 BaseClient.LoginSrv.LoginSrv.CheckUserInfo(UserInfo ui) 位置 E:\project\连云港项目\邮储银行端\源代码\FinancialRegulation\BaseClient\Web References\LoginSrv\Reference.cs:行号 115
   在 BaseClient.LoginClient.CheckUserInfo(UserInfo ui) 位置 E:\project\连云港项目\邮储银行端\源代码\FinancialRegulation\BaseClient\LoginClient.cs:行号 49
   在 MainFrame.LoginVM.CheckLogin() 位置 E:\project\连云港项目\邮储银行端\源代码\FinancialRegulation\MainFrame\LoginVM.cs:行号 142
   在 MainFrame.LoginVM.Confirm() 位置 E:\project\连云港项目\邮储银行端\源代码\FinancialRegulation\MainFrame\LoginVM.cs:行号 223
2014/11/11 16:14:17:975,[5],[]:System.Web.Services.Protocols.SoapException: System.Web.Services.Protocols.SoapException: 服务器无法处理请求。 ---> IBatisNet.DataMapper.Exceptions.DataMapperException: Unable to open connection to "Microsoft SQL Server 2005, provider V2.0.50215.0 in framework .NET V2.0". ---> System.Data.SqlClient.SqlException: 在与 SQL Server 建立连接时出现与网络相关的或特定于实例的错误。未找到或无法访问服务器。请验证实例名称是否正确并且 SQL Server 已配置为允许远程连接。 (provider: Named Pipes Provider, error: 40 - 无法打开到 SQL Server 的连接) ---> System.ComponentModel.Win32Exception: 找不到网络路径。
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   在 System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   在 System.Data.SqlClient.TdsParser.Connect(ServerInfo serverInfo, SqlInternalConnectionTds connHandler, Boolean ignoreSniOpenTimeout, Int64 timerExpire, Boolean encrypt, Boolean trustServerCert, Boolean integratedSecurity, Boolean withFailover)
   在 System.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover)
   在 System.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
   在 System.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
   在 System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions)
   在 System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 IBatisNet.DataMapper.SqlMapSession.OpenConnection(String connectionString)
   --- 内部异常堆栈跟踪的结尾 ---
   在 IBatisNet.DataMapper.SqlMapSession.OpenConnection(String connectionString)
   在 IBatisNet.DataMapper.Commands.DbCommandDecorator.System.Data.IDbCommand.ExecuteReader()
   在 IBatisNet.DataMapper.MappedStatements.MappedStatement.RunQueryForList[T](RequestScope request, ISqlMapSession session, Object parameterObject, IList`1 resultObject, RowDelegate`1 rowDelegate)
   在 IBatisNet.DataMapper.MappedStatements.MappedStatement.ExecuteQueryForList[T](ISqlMapSession session, Object parameterObject)
   在 IBatisNet.DataMapper.SqlMapper.QueryForList[T](String statementName, Object parameterObject)
   在 Dao.LoginDao.CheckUserInfo(UserInfo ui) 位置 E:\project\连云港项目\邮储银行端\源代码\FinancialRegulation\DAO\LoginDao.cs:行号 19
   在 FinancialRegulationSRV.LoginSrv.CheckUserInfo(UserInfo ui) 位置 E:\project\连云港项目\邮储银行端\源代码\FinancialRegulation\FinancialRegulationSRV\LoginSrv.asmx.cs:行号 35
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Web.Services.Protocols.SoapHttpClientProtocol.ReadResponse(SoapClientMessage message, WebResponse response, Stream responseStream, Boolean asyncCall)
   在 System.Web.Services.Protocols.SoapHttpClientProtocol.Invoke(String methodName, Object[] parameters)
   在 BaseClient.LoginSrv.LoginSrv.CheckUserInfo(UserInfo ui) 位置 E:\project\连云港项目\邮储银行端\源代码\FinancialRegulation\BaseClient\Web References\LoginSrv\Reference.cs:行号 115
   在 BaseClient.LoginClient.CheckUserInfo(UserInfo ui) 位置 E:\project\连云港项目\邮储银行端\源代码\FinancialRegulation\BaseClient\LoginClient.cs:行号 49
   在 MainFrame.LoginVM.CheckLogin() 位置 E:\project\连云港项目\邮储银行端\源代码\FinancialRegulation\MainFrame\LoginVM.cs:行号 142
   在 MainFrame.LoginVM.Confirm() 位置 E:\project\连云港项目\邮储银行端\源代码\FinancialRegulation\MainFrame\LoginVM.cs:行号 223
2014/11/11 16:32:41:511,[5],[]:System.Net.Sockets.SocketException (0x80004005): 由于套接字没有连接并且(当使用一个 sendto 调用发送数据报套接字时)没有提供地址，发送或接收数据的请求没有被接受。
   在 System.Net.Sockets.Socket.Send(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Send(Byte[] buffer)
   在 Message.MessageSender.SendMessage(BaseRequest bmr, String WebsiteCode, String TellerCode) 位置 E:\project\连云港项目\邮储银行端\源代码\FinancialRegulation\Message\MessageSender.cs:行号 52
   在 FinancialRegulation.ViewModel.BaseVM`1.SendMessage[R](BaseRequest request, String WebsiteCode, String TellerCode) 位置 E:\project\连云港项目\邮储银行端\源代码\FinancialRegulation\FinancialRegulation\ViewModel\BaseVM.cs:行号 31
   在 FinancialRegulation.ViewModel.FundInfoCheckVM.SearchExecute() 位置 E:\project\连云港项目\邮储银行端\源代码\FinancialRegulation\FinancialRegulation\Page\Fund\FundInfoCheckVM.cs:行号 207
